In [90]:
# Тема “Вычисления с помощью Numpy”

In [91]:
# Задание 1
# Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [92]:
import numpy as np

In [93]:
# Создайте массив Numpy под названием a размером 5x2, 
# то есть состоящий из 5 строк и 2 столбцов. 
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
# а второй - числа 6, 8, 11, 10, 7. 

In [94]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [95]:
# Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
# Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
# Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [96]:
print('среднее значение по каждому признаку')
mean_a = a.mean(axis = 0)
print(mean_a)

print("Размерность a: {}".format(a.ndim))
print("Форма a: {}".format(a.shape))

print(f'строк(наблюдение) = {a.shape[0]}')
print(f'столбцов(признак) = {a.shape[1]}')

среднее значение по каждому признаку
[2.  8.4]
Размерность a: 2
Форма a: (5, 2)
строк(наблюдение) = 5
столбцов(признак) = 2


In [97]:
# Задание 2
# Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
# содержащиеся в массиве mean_a. 
# Вычисление должно производиться в одно действие. 
# Получившийся массив должен иметь размер 5x2.


In [98]:
a_centered =   a - mean_a
a_centered_1 = np.subtract(a, mean_a)
print(' a - mean_a \n', a_centered)
print('np.subtract(a, mean_a) \n', a_centered_1)

 a - mean_a 
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]
np.subtract(a, mean_a) 
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [99]:
# Задание 3
# Найдите скалярное произведение столбцов массива a_centered. 
# В результате должна получиться величина a_centered_sp. 


In [100]:
a_1 = a_centered[:, 0]
a_2 = a_centered[:, 1]
print(a_1)
print(a_2)
a_centered_sp = a_1 @ a_2
a_centered_sp_1 = np.dot(a_1,a_2)
print(a_centered_sp)
print(a_centered_sp_1)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]
8.0
8.0


In [101]:
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [102]:
N = a.shape[0]
print('наблюдение N =', N)
num_of_observations = a_centered_sp / (N-1)
print(num_of_observations)

наблюдение N = 5
2.0


In [103]:
# Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. 

# В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, 
# поэтому полученная нами величина является несмещенной оценкой ковариации.

# В этом задании проверьте получившееся число, 
# вычислив ковариацию еще одним способом - с помощью функции np.cov. 

# В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 

# В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации 
# будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [104]:
# несмещенная оценка ковариации
num_of_observations = a_centered_sp / (N-1)

In [105]:
# print(a)
# print(a.transpose())
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [106]:
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

In [107]:
# Тема “Работа с данными в Pandas”

In [108]:
# Задание 1
# Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 

In [170]:
import pandas as pd

In [171]:
# Создайте датафрейм authors со столбцами author_id и author_name, 
# в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [172]:
author = {
    "author_id": [1, 2, 3],
    "authors": ['Тургенев', 'Чехов', 'Островский']
}

author_df = pd.DataFrame(auth)

author_df

author_id     authors
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [173]:
# Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
# [1, 1, 1, 2, 2, 3, 3],
# ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
# [450, 300, 350, 500, 450, 370, 290].

In [174]:
book ={
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price":[450, 300, 350, 500, 450, 370, 290]
}

book_df = pd.DataFrame(book)

book_df

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [175]:
# Задание 2
# Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [176]:
authors_price = pd.merge(author_df, book_df, on='author_id', how='outer')
authors_price

author_id     authors            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [177]:
# Задание 3
# Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [178]:
top5 = authors_price.nlargest(5, "price")
top5

author_id     authors         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [179]:
# Задание 4
# Создайте датафрейм authors_stat на основе информации из authors_price. 
# В датафрейме authors_stat должны быть четыре столбца:
# author_name, min_price, max_price и mean_price,
# в которых должны содержаться соответственно имя автора, 
# минимальная, максимальная и средняя цена на книги этого автора.

In [180]:
df1 = authors_price.groupby('authors').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('authors').agg({'price':'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('authors').agg({'price':'mean'}).rename(columns={'price':'mean_price'})

authors_stat = pd.concat([df1,df2,df3], axis=1)

authors_stat

min_price  max_price  mean_price
authors                                     
Островский        290        370  330.000000
Тургенев          300        450  366.666667
Чехов             450        500  475.000000

In [181]:
# Задание 5**
# Создайте новый столбец в датафрейме authors_price под названием cover, 
# в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. 
# В этот столбец поместите данные из следующего списка:
# ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [189]:
cover = {
    "cover": ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
}

cover_df = pd.DataFrame(cover)

authors_price_cover_df = pd.concat([authors_price,cover_df], axis=1)

authors_price_cover_df

author_id     authors            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [ ]:
# Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

In [213]:
pd.pivot_table?

Signature:
pd.pivot_table(
    data,
    values=None,
    index=None,
    columns=None,
    aggfunc='mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types 

In [ ]:
# Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. 
# Используйте для этого функцию pd.pivot_table. 
# При этом столбцы должны называться "твердая" и "мягкая", 
# а индексами должны быть фамилии авторов. 
# Пропущенные значения стоимостей заполните нулями,
# при необходимости загрузите библиотеку Numpy.

In [212]:
book_info =  pd.pivot_table(authors_price_cover_df, values='price', index=['authors'], 
                            columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover       мягкая  твердая
authors                    
Островский     660        0
Тургенев       650      450
Чехов            0      950

In [ ]:
# Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". 

In [214]:
book_info.to_pickle("book_info.pkl")

In [ ]:
# Затем загрузите из этого файла датафрейм и назовите его book_info2. 

In [215]:
book_info_r = pd.read_pickle("book_info.pkl")

print(book_info_r)

cover       мягкая  твердая
authors                    
Островский     660        0
Тургенев       650      450
Чехов            0      950


In [ ]:
# Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [216]:
book_info==book_info_r

cover       мягкая  твердая
authors                    
Островский    True     True
Тургенев      True     True
Чехов         True     True